[package]
name = "c6-scheduler"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chrono = { workspace = true }
chrono-tz = { version = "0.10", features = ["serde"] }
cron = "0.16"
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
